# Generated by Django 2.1.7 on 2019-03-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190304_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.SmallIntegerField(blank=True, choices=[(2, 'student'), (1, 'professor'), (0, 'admin')]),
        ),
    ]
