# Generated by Django 2.1.7 on 2019-04-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20190404_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.FileField(blank=True, upload_to='user-profile-photos'),
        ),
    ]
