# Generated by Django 2.1.7 on 2019-04-03 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20190328_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='file',
            field=models.FileField(blank=True, upload_to='lms-lite/quizes'),
        ),
    ]
