# Generated by Django 2.1.7 on 2019-04-03 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20190403_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='file',
            field=models.FileField(blank=True, upload_to='quiz'),
        ),
    ]
