# Generated by Django 2.1.7 on 2019-04-30 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_quiz_average'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='average',
            field=models.FloatField(blank=True, default=-1, null=True),
        ),
    ]
