# Generated by Django 2.1.7 on 2019-04-30 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_auto_20190430_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='average',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
