# Generated by Django 2.1.7 on 2019-04-30 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_assignment_restrict_date'),
        ('courses', '0023_auto_20190430_1310'),
    ]

    operations = [
    ]
